"""create system_emails table

Revision ID: 1216ab445426
Revises: e4a1b9b7f93a
Create Date: 2026-04-13 16:11:49.283786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1216ab445426"
down_revision: Union[str, Sequence[str], None] = "e4a1b9b7f93a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplier_finance_photos")
    op.drop_table("supplier_default_users")
    op.drop_index(op.f("ix_price_analyses_analysis_date"), table_name="price_analyses")
    op.drop_index(op.f("ix_price_analyses_id"), table_name="price_analyses")
    op.drop_index(op.f("ix_price_analyses_quote_id"), table_name="price_analyses")
    op.drop_table("price_analyses")
    op.drop_index(op.f("ix_supplier_ratings_created_at"), table_name="supplier_ratings")
    op.drop_index(op.f("ix_supplier_ratings_id"), table_name="supplier_ratings")
    op.drop_index(op.f("ix_supplier_ratings_quote_id"), table_name="supplier_ratings")
    op.drop_index(
        op.f("ix_supplier_ratings_supplier_id"), table_name="supplier_ratings"
    )
    op.drop_table("supplier_ratings")
    op.drop_table("supplier_quote_price_rules")
    op.drop_index(op.f("ix_contracts_created_at"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_quote_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_supplier_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_supplier_quote_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_table("supplier_finance_payments")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("supplier_documents")
    op.drop_table("supplier_finance_invoices")
    op.drop_table("supplier_guarantees")
    op.drop_index(
        op.f("ix_quote_comparisons_created_at"), table_name="quote_comparisons"
    )
    op.drop_index(op.f("ix_quote_comparisons_id"), table_name="quote_comparisons")
    op.drop_index(op.f("ix_quote_comparisons_quote_id"), table_name="quote_comparisons")
    op.drop_table("quote_comparisons")
    op.drop_table("supplier_payment_accounts")
    op.drop_table("supplier_check_settings")
    op.drop_index(op.f("ix_system_emails_id"), table_name="system_emails")
    op.drop_table("system_emails")
    op.drop_index(op.f("ix_smtp_settings_id"), table_name="smtp_settings")
    op.drop_table("smtp_settings")
    op.drop_table("supplier_email_changes")
    op.alter_column(
        "companies",
        "hide_location",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "share_on_whatsapp",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("email_settings", "reply_to_email")
    op.drop_column("email_settings", "bounce_email")
    op.drop_column("email_settings", "mailbox_contract_email")
    op.drop_column("email_settings", "mail_domain")
    op.drop_column("email_settings", "mailbox_security_email")
    op.drop_column("email_settings", "mailbox_notifications_email")
    op.drop_column("email_settings", "mailbox_payment_email")
    op.drop_column("email_settings", "enable_list_unsubscribe")
    op.drop_column("email_settings", "mailbox_support_email")
    op.drop_column("email_settings", "max_emails_per_minute")
    op.drop_column("email_settings", "mailbox_action_email")
    op.drop_column("email_settings", "mailbox_quote_email")
    op.drop_column("email_settings", "enable_strict_from_alignment")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_settings",
        sa.Column(
            "enable_strict_from_alignment",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_quote_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_action_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "max_emails_per_minute",
            sa.INTEGER(),
            server_default=sa.text("30"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_support_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "enable_list_unsubscribe",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_payment_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_notifications_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_security_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mail_domain", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "mailbox_contract_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "bounce_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "email_settings",
        sa.Column(
            "reply_to_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "companies",
        "share_on_whatsapp",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "hide_location",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_table(
        "supplier_email_changes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "supplier_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("old_email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("new_email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("expires_at", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("used_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_email_changes_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("supplier_email_changes_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "smtp_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "smtp_host", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("smtp_port", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "smtp_username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "smtp_password", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "from_email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "from_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("use_tls", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("use_ssl", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "enable_email_notifications",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("smtp_settings_pkey")),
    )
    op.create_index(op.f("ix_smtp_settings_id"), "smtp_settings", ["id"], unique=False)
    op.create_table(
        "system_emails",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("system_emails_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("system_emails_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_system_emails_id"), "system_emails", ["id"], unique=False)
    op.create_table(
        "supplier_check_settings",
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "accepts_checks",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("preferred_term", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "supplier_id", name=op.f("supplier_check_settings_pkey")
        ),
    )
    op.create_table(
        "supplier_payment_accounts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bank_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("bank_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("iban", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("account_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_payment_accounts_pkey")),
    )
    op.create_table(
        "quote_comparisons",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("comparison_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("metric_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metric_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "winner_supplier_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("quote_comparisons_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["winner_supplier_id"],
            ["suppliers.id"],
            name=op.f("quote_comparisons_winner_supplier_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("quote_comparisons_pkey")),
    )
    op.create_index(
        op.f("ix_quote_comparisons_quote_id"),
        "quote_comparisons",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quote_comparisons_id"), "quote_comparisons", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_quote_comparisons_created_at"),
        "quote_comparisons",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "supplier_guarantees",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("guarantee_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("issued_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expires_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'active'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expired_notified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_guarantees_pkey")),
    )
    op.create_table(
        "supplier_finance_invoices",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("invoice_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("invoice_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_invoices_pkey")),
    )
    op.create_table(
        "supplier_documents",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("original_filename", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("stored_filename", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("content_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_documents_pkey")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "jti_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("refresh_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_jti_hash"), "refresh_tokens", ["jti_hash"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_table(
        "supplier_finance_payments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("payment_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("method", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_payments_pkey")),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "supplier_quote_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contract_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "total_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "discount_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "final_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("payment_terms", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "delivery_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("warranty_period", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("pdf_file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "signed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("signed_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("contracts_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["signed_by_id"], ["users.id"], name=op.f("contracts_signed_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("contracts_supplier_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_quote_id"],
            ["supplier_quotes.id"],
            name=op.f("contracts_supplier_quote_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("contracts_pkey")),
    )
    op.create_index(
        op.f("ix_contracts_supplier_quote_id"),
        "contracts",
        ["supplier_quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contracts_supplier_id"), "contracts", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_quote_id"), "contracts", ["quote_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_id"), "contracts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contracts_created_at"), "contracts", ["created_at"], unique=False
    )
    op.create_table(
        "supplier_quote_price_rules",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "max_markup_percent",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("25"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_discount_percent",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("35"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tolerance_amount",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "block_on_violation",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_quote_price_rules_pkey")),
    )
    op.create_table(
        "supplier_ratings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rated_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("price_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("delivery_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quality_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "communication_rating", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "overall_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("supplier_ratings_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["rated_by_id"],
            ["users.id"],
            name=op.f("supplier_ratings_rated_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("supplier_ratings_supplier_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_ratings_pkey")),
    )
    op.create_index(
        op.f("ix_supplier_ratings_supplier_id"),
        "supplier_ratings",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_ratings_quote_id"),
        "supplier_ratings",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_ratings_id"), "supplier_ratings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_ratings_created_at"),
        "supplier_ratings",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "price_analyses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "min_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "avg_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "median_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "price_variance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cheapest_supplier_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "most_expensive_supplier_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_responses", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "submitted_responses", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "analysis_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cheapest_supplier_id"],
            ["suppliers.id"],
            name=op.f("price_analyses_cheapest_supplier_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["most_expensive_supplier_id"],
            ["suppliers.id"],
            name=op.f("price_analyses_most_expensive_supplier_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("price_analyses_quote_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("price_analyses_pkey")),
    )
    op.create_index(
        op.f("ix_price_analyses_quote_id"), "price_analyses", ["quote_id"], unique=False
    )
    op.create_index(
        op.f("ix_price_analyses_id"), "price_analyses", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_price_analyses_analysis_date"),
        "price_analyses",
        ["analysis_date"],
        unique=False,
    )
    op.create_table(
        "supplier_default_users",
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "supplier_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "supplier_id", name=op.f("supplier_default_users_pkey")
        ),
    )
    op.create_table(
        "supplier_finance_photos",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_photos_pkey")),
    )
    # ### end Alembic commands ###
