"""init tables

Revision ID: 12609f3c5e9d
Revises: db5bc75280a0
Create Date: 2026-03-26 20:43:08.447461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12609f3c5e9d"
down_revision: Union[str, Sequence[str], None] = "db5bc75280a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.add_column("quotes", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("quotes", sa.Column("title", sa.String(), nullable=False))
    op.add_column(
        "quotes",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.create_foreign_key(None, "quotes", "users", ["user_id"], ["id"])
    op.drop_column("quotes", "vendor")
    op.drop_column("quotes", "currency")
    op.drop_column("quotes", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quotes", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "quotes",
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quotes", sa.Column("vendor", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_column("quotes", "created_at")
    op.drop_column("quotes", "title")
    op.drop_column("quotes", "user_id")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
