"""add_department_id_to_company_roles

Revision ID: 25b2def06025
Revises: 9bac61044cb0
Create Date: 2026-04-08 21:19:26.020856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25b2def06025"
down_revision: Union[str, Sequence[str], None] = "9bac61044cb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplier_documents")
    op.drop_table("supplier_payment_accounts")
    op.drop_index(op.f("ix_refresh_tokens_jti_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("supplier_finance_payments")
    op.drop_table("supplier_guarantees")
    op.drop_index(op.f("ix_supplier_ratings_created_at"), table_name="supplier_ratings")
    op.drop_index(op.f("ix_supplier_ratings_id"), table_name="supplier_ratings")
    op.drop_index(op.f("ix_supplier_ratings_quote_id"), table_name="supplier_ratings")
    op.drop_index(
        op.f("ix_supplier_ratings_supplier_id"), table_name="supplier_ratings"
    )
    op.drop_table("supplier_ratings")
    op.drop_table("supplier_finance_invoices")
    op.drop_table("supplier_check_settings")
    op.drop_table("supplier_default_users")
    op.drop_table("supplier_finance_photos")
    op.drop_index(op.f("ix_price_analyses_analysis_date"), table_name="price_analyses")
    op.drop_index(op.f("ix_price_analyses_id"), table_name="price_analyses")
    op.drop_index(op.f("ix_price_analyses_quote_id"), table_name="price_analyses")
    op.drop_table("price_analyses")
    op.drop_table("supplier_email_changes")
    op.drop_index(
        op.f("ix_quote_comparisons_created_at"), table_name="quote_comparisons"
    )
    op.drop_index(op.f("ix_quote_comparisons_id"), table_name="quote_comparisons")
    op.drop_index(op.f("ix_quote_comparisons_quote_id"), table_name="quote_comparisons")
    op.drop_table("quote_comparisons")
    op.drop_index(op.f("ix_contracts_created_at"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_quote_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_supplier_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_supplier_quote_id"), table_name="contracts")
    op.drop_table("contracts")
    op.alter_column(
        "companies",
        "color",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=7),
        nullable=False,
    )
    op.add_column(
        "company_roles", sa.Column("department_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "company_roles", "departments", ["department_id"], ["id"]
    )
    op.alter_column(
        "projects",
        "address",
        existing_type=sa.VARCHAR(length=500),
        comment="Proje adresi",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Google Maps lat",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Google Maps lng",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "project_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        comment="Proje tipi: 'merkez' veya 'franchise'",
    )
    op.alter_column(
        "projects",
        "manager_name",
        existing_type=sa.VARCHAR(length=255),
        comment="Proje yetkilisi adı",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "manager_phone",
        existing_type=sa.VARCHAR(length=20),
        comment="Proje yetkilisi telefon",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "manager_email",
        existing_type=sa.VARCHAR(length=255),
        comment="Proje yetkilisi e-mail",
        existing_nullable=True,
    )
    op.alter_column("quotes", "project_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "quotes", "created_by_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "quotes",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        type_=sa.Enum(
            "draft",
            "submitted",
            "pending",
            "responded",
            "approved",
            "rejected",
            name="quotestatus",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "quotes", "company_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "quotes",
        "company_contact_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "quotes",
        "company_contact_phone",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "quotes",
        "company_contact_email",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "quotes",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "quotes",
        "total_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    op.alter_column(
        "quotes", "currency", existing_type=sa.VARCHAR(length=3), nullable=False
    )
    op.alter_column("quotes", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_quotes_status"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_user_id"), table_name="quotes")
    op.create_index(
        op.f("ix_quotes_project_id"), "quotes", ["project_id"], unique=False
    )
    op.create_foreign_key(None, "quotes", "users", ["created_by_id"], ["id"])
    op.create_foreign_key(None, "quotes", "users", ["assigned_to_id"], ["id"])
    op.create_foreign_key(None, "quotes", "projects", ["project_id"], ["id"])
    op.create_foreign_key(None, "quotes", "departments", ["department_id"], ["id"])
    op.alter_column(
        "users",
        "approval_limit",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Onay limitini TL cinsinden",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "approval_limit",
        existing_type=sa.INTEGER(),
        server_default=sa.text("100000"),
        existing_comment="Onay limitini TL cinsinden",
        existing_nullable=False,
    )
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_index(op.f("ix_quotes_project_id"), table_name="quotes")
    op.create_index(op.f("ix_quotes_user_id"), "quotes", ["user_id"], unique=False)
    op.create_index(op.f("ix_quotes_status"), "quotes", ["status"], unique=False)
    op.alter_column("quotes", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "quotes", "currency", existing_type=sa.VARCHAR(length=3), nullable=True
    )
    op.alter_column(
        "quotes",
        "total_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    op.alter_column(
        "quotes",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "quotes",
        "company_contact_email",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "quotes",
        "company_contact_phone",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "quotes",
        "company_contact_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "quotes", "company_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "quotes",
        "status",
        existing_type=sa.Enum(
            "draft",
            "submitted",
            "pending",
            "responded",
            "approved",
            "rejected",
            name="quotestatus",
            native_enum=False,
        ),
        server_default=sa.text("'draft'::character varying"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "quotes", "created_by_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("quotes", "project_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "projects",
        "manager_email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Proje yetkilisi e-mail",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "manager_phone",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Proje yetkilisi telefon",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "manager_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Proje yetkilisi adı",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "project_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        comment=None,
        existing_comment="Proje tipi: 'merkez' veya 'franchise'",
    )
    op.alter_column(
        "projects",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Google Maps lng",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Google Maps lat",
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "address",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Proje adresi",
        existing_nullable=True,
    )
    op.drop_constraint(None, "company_roles", type_="foreignkey")
    op.drop_column("company_roles", "department_id")
    op.alter_column(
        "companies",
        "color",
        existing_type=sa.String(length=7),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "supplier_quote_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contract_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "total_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "discount_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "final_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("payment_terms", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "delivery_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("warranty_period", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("pdf_file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "signed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("signed_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("contracts_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["signed_by_id"], ["users.id"], name=op.f("contracts_signed_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("contracts_supplier_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_quote_id"],
            ["supplier_quotes.id"],
            name=op.f("contracts_supplier_quote_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("contracts_pkey")),
    )
    op.create_index(
        op.f("ix_contracts_supplier_quote_id"),
        "contracts",
        ["supplier_quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contracts_supplier_id"), "contracts", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_quote_id"), "contracts", ["quote_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_id"), "contracts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contracts_created_at"), "contracts", ["created_at"], unique=False
    )
    op.create_table(
        "quote_comparisons",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("comparison_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("metric_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metric_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "winner_supplier_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("quote_comparisons_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["winner_supplier_id"],
            ["suppliers.id"],
            name=op.f("quote_comparisons_winner_supplier_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("quote_comparisons_pkey")),
    )
    op.create_index(
        op.f("ix_quote_comparisons_quote_id"),
        "quote_comparisons",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quote_comparisons_id"), "quote_comparisons", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_quote_comparisons_created_at"),
        "quote_comparisons",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "supplier_email_changes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "supplier_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("old_email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("new_email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("expires_at", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("used_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_email_changes_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("supplier_email_changes_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "price_analyses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "min_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "avg_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "median_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "price_variance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cheapest_supplier_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "most_expensive_supplier_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_responses", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "submitted_responses", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "analysis_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cheapest_supplier_id"],
            ["suppliers.id"],
            name=op.f("price_analyses_cheapest_supplier_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["most_expensive_supplier_id"],
            ["suppliers.id"],
            name=op.f("price_analyses_most_expensive_supplier_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("price_analyses_quote_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("price_analyses_pkey")),
    )
    op.create_index(
        op.f("ix_price_analyses_quote_id"), "price_analyses", ["quote_id"], unique=False
    )
    op.create_index(
        op.f("ix_price_analyses_id"), "price_analyses", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_price_analyses_analysis_date"),
        "price_analyses",
        ["analysis_date"],
        unique=False,
    )
    op.create_table(
        "supplier_finance_photos",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_photos_pkey")),
    )
    op.create_table(
        "supplier_default_users",
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "supplier_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "supplier_id", name=op.f("supplier_default_users_pkey")
        ),
    )
    op.create_table(
        "supplier_check_settings",
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "accepts_checks",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("preferred_term", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "supplier_id", name=op.f("supplier_check_settings_pkey")
        ),
    )
    op.create_table(
        "supplier_finance_invoices",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("invoice_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("invoice_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_invoices_pkey")),
    )
    op.create_table(
        "supplier_ratings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rated_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("price_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("delivery_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quality_rating", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "communication_rating", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "overall_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("supplier_ratings_quote_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["rated_by_id"],
            ["users.id"],
            name=op.f("supplier_ratings_rated_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("supplier_ratings_supplier_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_ratings_pkey")),
    )
    op.create_index(
        op.f("ix_supplier_ratings_supplier_id"),
        "supplier_ratings",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_ratings_quote_id"),
        "supplier_ratings",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_ratings_id"), "supplier_ratings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_ratings_created_at"),
        "supplier_ratings",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "supplier_guarantees",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("guarantee_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("issued_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expires_at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'active'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expired_notified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_guarantees_pkey")),
    )
    op.create_table(
        "supplier_finance_payments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("payment_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.TEXT(),
            server_default=sa.text("'TRY'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("method", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_finance_payments_pkey")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "jti_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("refresh_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_tokens_pkey")),
        sa.UniqueConstraint(
            "jti_hash",
            name=op.f("refresh_tokens_jti_hash_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_jti_hash"), "refresh_tokens", ["jti_hash"], unique=False
    )
    op.create_table(
        "supplier_payment_accounts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bank_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("bank_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("iban", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("account_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_payment_accounts_pkey")),
    )
    op.create_table(
        "supplier_documents",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("original_filename", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("stored_filename", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("content_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("supplier_documents_pkey")),
    )
    # ### end Alembic commands ###
