"""Add department, project models and update user schema

Revision ID: 70522496b0f3
Revises: 5f450f44eaf5
Create Date: 2026-03-30 20:36:01.373706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "70522496b0f3"
down_revision: Union[str, Sequence[str], None] = "5f450f44eaf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "user_projects",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "project_id"),
    )
    op.add_column(
        "quotes",
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    op.add_column(
        "quotes", sa.Column("transition_reason", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "approval_limit",
            sa.Integer(),
            server_default=sa.text("100000"),
            nullable=False,
            comment="Onay limitini TL cinsinden",
        ),
    )
    op.add_column("users", sa.Column("department_id", sa.Integer(), nullable=True))
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=50),
        comment="Role: super_admin, satinalma_direktoru, satinalma_yoneticisi, satinalma_uzmani, satinalmaci",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "users", "departments", ["department_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Role: super_admin, satinalma_direktoru, satinalma_yoneticisi, satinalma_uzmani, satinalmaci",
        existing_nullable=False,
    )
    op.drop_column("users", "department_id")
    op.drop_column("users", "approval_limit")
    op.drop_column("quotes", "transition_reason")
    op.drop_column("quotes", "version")
    op.drop_table("user_projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
