"""add quote status logs table

Revision ID: c774495be545
Revises: 80ffd3de3142
Create Date: 2026-03-27 15:34:48.105661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c774495be545"
down_revision: Union[str, Sequence[str], None] = "80ffd3de3142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_status_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=False),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quote_status_logs_changed_by"),
        "quote_status_logs",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quote_status_logs_id"), "quote_status_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_quote_status_logs_quote_id"),
        "quote_status_logs",
        ["quote_id"],
        unique=False,
    )
    op.add_column(
        "quotes", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "quotes", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("quotes", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("quotes", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column("quotes", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.alter_column("quotes", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "quotes",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "quotes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_quotes_user_id"), "quotes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quotes_user_id"), table_name="quotes")
    op.alter_column(
        "quotes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "quotes",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column("quotes", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("quotes", "deleted_by")
    op.drop_column("quotes", "updated_by")
    op.drop_column("quotes", "created_by")
    op.drop_column("quotes", "deleted_at")
    op.drop_column("quotes", "updated_at")
    op.drop_index(op.f("ix_quote_status_logs_quote_id"), table_name="quote_status_logs")
    op.drop_index(op.f("ix_quote_status_logs_id"), table_name="quote_status_logs")
    op.drop_index(
        op.f("ix_quote_status_logs_changed_by"), table_name="quote_status_logs"
    )
    op.drop_table("quote_status_logs")
    # ### end Alembic commands ###
