[mypy]
python_version = 3.11
mypy_path = .
files = api
namespace_packages = True
explicit_package_bases = True
warn_unused_configs = True
pretty = True
show_error_codes = True
exclude = (?x)(^api/alembic/|^api/scripts/debug/)
no_implicit_optional = False

[mypy-jose.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True
