from __future__ import annotations

import importlib.util


PROVIDER_DEFINITIONS: list[dict] = [
    {
        "code": "iyzico",
        "name": "iyzico",
        "country": "TR",
        "category": "card_checkout",
        "integration_level": "implemented",
        "installed": importlib.util.find_spec("iyzipay") is not None,
        "default_active": True,
        "supports": ["card", "installment", "hosted_checkout", "subscription_manual"],
        "notes": "Turkiye icin ilk tercih. Checkout Form iskeleti hazir.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "IYZICO_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "IYZICO_SECRET_KEY",
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "secret": False,
                "required": True,
                "placeholder": "https://sandbox.iyzipay.com",
            },
        ],
    },
    {
        "code": "paytr",
        "name": "PayTR",
        "country": "TR",
        "category": "card_checkout",
        "integration_level": "skeleton",
        "installed": True,
        "default_active": False,
        "supports": ["card", "installment", "iframe_checkout"],
        "notes": "PayTR magaza no, magaza parola ve magaza gizli anahtari ile calisir.",
        "fields": [
            {
                "key": "merchant_id",
                "label": "Magaza No",
                "secret": False,
                "required": True,
                "placeholder": "PAYTR_MERCHANT_ID",
            },
            {
                "key": "merchant_key",
                "label": "Magaza Parola",
                "secret": True,
                "required": True,
                "placeholder": "PAYTR_MERCHANT_KEY",
            },
            {
                "key": "merchant_salt",
                "label": "Magaza Gizli Anahtari",
                "secret": True,
                "required": True,
                "placeholder": "PAYTR_MERCHANT_SALT",
            },
        ],
    },
    {
        "code": "param",
        "name": "ParamPOS",
        "country": "TR",
        "category": "virtual_pos",
        "integration_level": "skeleton",
        "installed": True,
        "default_active": False,
        "supports": ["card", "virtual_pos", "multi_bank"],
        "notes": "Kurumsal sanal POS senaryolari icin uygun.",
        "fields": [
            {
                "key": "client_code",
                "label": "Client Code",
                "secret": False,
                "required": True,
                "placeholder": "PARAM_CLIENT_CODE",
            },
            {
                "key": "username",
                "label": "Kullanici Adi",
                "secret": False,
                "required": True,
                "placeholder": "PARAM_USERNAME",
            },
            {
                "key": "guid",
                "label": "GUID",
                "secret": True,
                "required": True,
                "placeholder": "PARAM_GUID",
            },
        ],
    },
    {
        "code": "sipay",
        "name": "Sipay",
        "country": "TR",
        "category": "payment_orchestration",
        "integration_level": "skeleton",
        "installed": True,
        "default_active": False,
        "supports": ["card", "link_payment", "marketplace"],
        "notes": "Yeni nesil odeme orkestrasyonu ve marketplace akislarina uygun.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "SIPAY_API_KEY",
            },
            {
                "key": "api_secret",
                "label": "API Secret",
                "secret": True,
                "required": True,
                "placeholder": "SIPAY_API_SECRET",
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "secret": False,
                "required": False,
                "placeholder": "https://api.sipay.com.tr",
            },
        ],
    },
    {
        "code": "bank_transfer",
        "name": "Havale / EFT",
        "country": "TR",
        "category": "manual",
        "integration_level": "implemented",
        "installed": True,
        "default_active": True,
        "supports": ["manual_approval", "invoice_collection"],
        "notes": "Banka hesap bilgileri paylasilarak manuel odeme toplanir.",
        "fields": [
            {
                "key": "bank_name",
                "label": "Banka Adi",
                "secret": False,
                "required": True,
                "placeholder": "Ornek Bankasi",
            },
            {
                "key": "iban",
                "label": "IBAN",
                "secret": False,
                "required": True,
                "placeholder": "TR00 0000...",
            },
            {
                "key": "account_name",
                "label": "Hesap Unvani",
                "secret": False,
                "required": False,
                "placeholder": "BUYER ASISTANS",
            },
        ],
    },
    {
        "code": "paypal",
        "name": "PayPal",
        "country": "GLOBAL",
        "category": "wallet",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["wallet", "cross_border"],
        "notes": "Turkiye ic pazar odemeleri icin birincil secenek degil.",
        "fields": [
            {
                "key": "client_id",
                "label": "Client ID",
                "secret": True,
                "required": True,
                "placeholder": "PAYPAL_CLIENT_ID",
            },
            {
                "key": "client_secret",
                "label": "Client Secret",
                "secret": True,
                "required": True,
                "placeholder": "PAYPAL_CLIENT_SECRET",
            },
            {
                "key": "mode",
                "label": "Mode",
                "secret": False,
                "required": False,
                "placeholder": "sandbox",
            },
        ],
    },
    {
        "code": "mexc",
        "name": "MEXC",
        "country": "GLOBAL",
        "category": "crypto_exchange",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["crypto", "exchange_transfer"],
        "notes": "Kripto tahsilat/transfer akisi icin borsa baglantisi.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "MEXC_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "MEXC_SECRET_KEY",
            },
            {
                "key": "wallet_address",
                "label": "Cuzdan Adresi",
                "secret": False,
                "required": False,
                "placeholder": "USDT...",
            },
            {
                "key": "network",
                "label": "Ag",
                "secret": False,
                "required": False,
                "placeholder": "TRC20",
            },
        ],
    },
    {
        "code": "binance",
        "name": "Binance",
        "country": "GLOBAL",
        "category": "crypto_exchange",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["crypto", "exchange_transfer", "binance_pay"],
        "notes": "Kripto tahsilat/transfer akisi icin borsa baglantisi.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "BINANCE_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "BINANCE_SECRET_KEY",
            },
            {
                "key": "wallet_address",
                "label": "Cuzdan Adresi",
                "secret": False,
                "required": False,
                "placeholder": "USDT...",
            },
            {
                "key": "network",
                "label": "Ag",
                "secret": False,
                "required": False,
                "placeholder": "BSC",
            },
        ],
    },
    {
        "code": "okx",
        "name": "OKX",
        "country": "GLOBAL",
        "category": "crypto_exchange",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["crypto", "exchange_transfer"],
        "notes": "Kripto tahsilat/transfer akisi icin borsa baglantisi.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "OKX_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "OKX_SECRET_KEY",
            },
            {
                "key": "passphrase",
                "label": "Passphrase",
                "secret": True,
                "required": True,
                "placeholder": "OKX_PASSPHRASE",
            },
            {
                "key": "wallet_address",
                "label": "Cuzdan Adresi",
                "secret": False,
                "required": False,
                "placeholder": "USDT...",
            },
        ],
    },
    {
        "code": "bybit",
        "name": "Bybit",
        "country": "GLOBAL",
        "category": "crypto_exchange",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["crypto", "exchange_transfer"],
        "notes": "Kripto tahsilat/transfer akisi icin borsa baglantisi.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "BYBIT_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "BYBIT_SECRET_KEY",
            },
            {
                "key": "wallet_address",
                "label": "Cuzdan Adresi",
                "secret": False,
                "required": False,
                "placeholder": "USDT...",
            },
            {
                "key": "network",
                "label": "Ag",
                "secret": False,
                "required": False,
                "placeholder": "TRC20",
            },
        ],
    },
    {
        "code": "bitget",
        "name": "Bitget",
        "country": "GLOBAL",
        "category": "crypto_exchange",
        "integration_level": "backlog",
        "installed": True,
        "default_active": False,
        "supports": ["crypto", "exchange_transfer"],
        "notes": "Kripto tahsilat/transfer akisi icin borsa baglantisi.",
        "fields": [
            {
                "key": "api_key",
                "label": "API Key",
                "secret": True,
                "required": True,
                "placeholder": "BITGET_API_KEY",
            },
            {
                "key": "secret_key",
                "label": "Secret Key",
                "secret": True,
                "required": True,
                "placeholder": "BITGET_SECRET_KEY",
            },
            {
                "key": "passphrase",
                "label": "Passphrase",
                "secret": True,
                "required": False,
                "placeholder": "BITGET_PASSPHRASE",
            },
            {
                "key": "wallet_address",
                "label": "Cuzdan Adresi",
                "secret": False,
                "required": False,
                "placeholder": "USDT...",
            },
        ],
    },
]


def build_payment_provider_catalog() -> list[dict]:
    return PROVIDER_DEFINITIONS
